name: social_connect_hub
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^12.1.1
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  json_annotation: ^4.8.1
  # State Management
  provider: ^6.1.4
  get_it: ^8.0.3
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  shared_preferences: ^2.2.0
  equatable: ^2.0.7
  jose: ^0.3.4
  url_launcher: ^6.3.1
  file_picker: ^8.3.2
  mime: ^1.0.6
  vector_math: ^2.1.4
  image_picker: ^1.1.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "generated-icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "app_icon.svg"
    background_color: "#1A73E8"
    theme_color: "#1A73E8"


  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.11


flutter:

  uses-material-design: true

