// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Cy9ucJEsX5BYlUZqAfQkKVBBZbctWJo',
    appId: '1:260086352966:web:2890e605913bef27a08e47',
    messagingSenderId: '260086352966',
    projectId: 'vipulconnecthub',
    authDomain: 'vipulconnecthub.firebaseapp.com',
    storageBucket: 'vipulconnecthub.firebasestorage.app',
    measurementId: 'G-R436EY8QCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHqbTHT-wM0W0qnugsOTITP5_bPdNJ6TY',
    appId: '1:260086352966:android:9d4241f2be088678a08e47',
    messagingSenderId: '260086352966',
    projectId: 'vipulconnecthub',
    storageBucket: 'vipulconnecthub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnUwZpgXD1Zn98eHkCIG_yro5h09UjumE',
    appId: '1:260086352966:ios:e7a12f0dce51f44aa08e47',
    messagingSenderId: '260086352966',
    projectId: 'vipulconnecthub',
    storageBucket: 'vipulconnecthub.firebasestorage.app',
    iosBundleId: 'com.vipulsoftwares.socialConnectHub',
  );
}
